### ISSUE TITLE
I saw nothing change on the web server

### ISSUE THREAD

**Issue by liuhantao9** [punkyoon/live-graph#1]
I tested you code but the plot is not moving. I am trying to figure out the reason. It seems like every time I click the start button. The client side froze for some reason. Can you help?

**Comment by punkyoon** [comment]
hi, plz follow these guide

1. install python pacakages (i recommend you to use python version 3)

```bash
$ pip install -r requirements.txt
```

2. run server

```bash
$ python server.py
```

3. open `localhost:8000` and click **start** button

> the purpose of **start** button is to get socket.io messages from client and show them through the plot.

4. uncomment **time.sleep(0.5)** in `client_test.py`

```python
...
while True:
    with SocketIO('localhost', 8000, LoggingNamespace) as socketIO:
        # test data set
        send_data = {
            'e': randrange(10),
            'walk': randrange(50),
            'fast_walk': randrange(50),
            'walk_time': randrange(50),
            'fast_walk_time': randrange(50),
            'rest_time': randrange(50),
        }

        # sending data set
        socketIO.emit('my event', send_data)
        time.sleep(0.5)    # <<<--- HERE!!!
...
```

5. run client test code

```bash
$ python client_test.py
```

then, you can check the plot is moving smoothly.

**Comment by punkyoon** [comment]
https://github.com/liuhantao9/plotly-js-graph-realtime

ㅋㅋㅋㅋ
